# Generated by Django 5.1.15 on 2026-05-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('festivals', '0001_initial'),
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='films',
            field=models.ManyToManyField(blank=True, related_name='festivals', to='films.film'),
        ),
    ]
