# Generated by Django 5.1.15 on 2026-05-28 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0007_actor_birthday_actor_deathday_actor_facebook_id_and_more'),
        ('festivals', '0002_initial'),
        ('films', '0005_film_episodes_count_film_is_tv_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='festival',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='festival',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='logo_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='festival',
            name='native_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='festival',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='festival',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='festival',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='FestivalAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('award_type', models.CharField(choices=[('winner', 'Winner'), ('nominee', 'Nominee')], default='winner', max_length=50)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='festival_awards', to='actors.actor')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='festivals.festival')),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='festival_awards', to='films.film')),
            ],
        ),
    ]
