# Generated by Django 5.1.15 on 2026-05-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0003_festival_city_festival_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='festivals/logos/'),
        ),
    ]
