# Generated by Django 5.1.15 on 2026-05-28 08:24

import apps.festivals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0004_festival_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.festivals.models.festival_logo_upload_path),
        ),
    ]
