# Generated by Django 5.1.15 on 2026-05-30 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0005_alter_festival_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='festival',
            old_name='logo',
            new_name='local_logo',
        ),
        migrations.RenameField(
            model_name='festival',
            old_name='logo_path',
            new_name='tmdb_logo',
        ),
    ]
