# Generated by Django 5.1.15 on 2026-05-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pref_duration',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pref_era',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pref_genres',
            field=models.ManyToManyField(blank=True, related_name='preferred_by', to='films.genre'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pref_min_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pref_mood',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
