# Generated by Django 5.1.15 on 2026-05-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_pref_duration_userprofile_pref_era_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pref_mood',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pref_focus',
            field=models.CharField(blank=True, choices=[('rating', 'Rating Tertinggi'), ('popular', 'Paling Populer'), ('genre', 'Sesuai Genre'), ('balanced', 'Seimbang')], default='balanced', max_length=20),
        ),
    ]
