# Generated by Django 5.1.15 on 2026-05-25 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_pref_mood_userprofile_pref_focus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pref_min_rating',
        ),
    ]
