# Generated by Django 5.1.15 on 2026-05-28 08:24

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_avatar_path_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.user_avatar_upload_path),
        ),
    ]
