# Generated by Django 5.1.15 on 2026-05-24 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('festivals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tmdb_genre_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField(blank=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('trailer_url', models.URLField(blank=True, max_length=500)),
                ('poster_path', models.CharField(blank=True, max_length=255)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('popularity', models.FloatField(default=0.0)),
                ('avg_rating', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='films', to='festivals.studio')),
                ('genre', models.ManyToManyField(blank=True, related_name='films', to='films.genre')),
            ],
        ),
    ]
