# Generated by Django 5.1.15 on 2026-05-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_filmimage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filmimage',
            unique_together={('film', 'file_path')},
        ),
        migrations.AddIndex(
            model_name='filmimage',
            index=models.Index(fields=['film', 'file_path'], name='films_filmi_film_id_03b6ea_idx'),
        ),
    ]
