# Generated by Django 5.1.15 on 2026-05-25 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_filmimage_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='films_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='film',
            name='is_local_edit',
            field=models.BooleanField(default=False, help_text='Apakah film ini punya edit lokal (bukan dari TMDB)'),
        ),
        migrations.AddField(
            model_name='film',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Alasan penolakan film'),
        ),
        migrations.AddField(
            model_name='film',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('published', 'Published'), ('rejected', 'Rejected')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='film',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='film',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='films_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
