# Generated by Django 5.1.15 on 2026-05-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_film_created_by_film_is_local_edit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='episodes_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='is_tv_series',
            field=models.BooleanField(default=False),
        ),
    ]
