# Generated by Django 5.1.15 on 2026-05-28 08:27

import apps.films.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_film_episodes_count_film_is_tv_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=apps.films.models.film_poster_upload_path),
        ),
    ]
