# Generated by Django 5.1.15 on 2026-05-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_film_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='popularity',
            new_name='tmdb_popularity',
        ),
        migrations.AddField(
            model_name='film',
            name='local_popularity',
            field=models.FloatField(default=0.0),
        ),
    ]
