# Generated by Django 5.1.15 on 2026-05-30 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_rename_popularity_film_tmdb_popularity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='poster',
            new_name='local_poster',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='poster_path',
            new_name='tmdb_poster',
        ),
    ]
