# Generated by Django 5.1.15 on 2026-05-24 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='genre_spec',
            field=models.ManyToManyField(blank=True, related_name='actors', to='films.genre'),
        ),
        migrations.AddField(
            model_name='filmography',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmographies', to='actors.actor'),
        ),
        migrations.AddField(
            model_name='filmography',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmographies', to='films.film'),
        ),
        migrations.AlterUniqueTogether(
            name='filmography',
            unique_together={('actor', 'film', 'role')},
        ),
    ]
