# Generated by Django 5.1.15 on 2026-05-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='native_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
