# Generated by Django 5.1.15 on 2026-05-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_add_native_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmography',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
