# Generated by Django 5.1.15 on 2026-05-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0005_actor_created_at_actor_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmography',
            name='role_type',
            field=models.CharField(choices=[('lead', 'Pemeran Utama'), ('supporting', 'Pemeran Pendukung'), ('cameo', 'Kameo'), ('director', 'Sutradara'), ('producer', 'Produser'), ('writer', 'Penulis Skenario'), ('other', 'Lainnya')], default='supporting', max_length=20),
        ),
    ]
