# Generated by Django 5.1.15 on 2026-05-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0006_filmography_role_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='deathday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Not specified'), (1, 'Female'), (2, 'Male'), (3, 'Non-binary')], null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='known_for_department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='tiktok_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
