# Generated by Django 5.1.15 on 2026-05-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0007_actor_birthday_actor_deathday_actor_facebook_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='actors/photos/'),
        ),
    ]
