# Generated by Django 5.1.15 on 2026-05-28 08:24

import apps.actors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0008_actor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.actors.models.actor_photo_upload_path),
        ),
    ]
