# Generated by Django 5.1.15 on 2026-05-30 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0009_alter_actor_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='photo',
            new_name='local_photo',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='photo_path',
            new_name='tmdb_photo',
        ),
    ]
